"""
Instructions to install PyTorch with CUDA support
"""

print("="*70)
print("GPU Installation Guide")
print("="*70)
print("\nYour system:")
print("  - GPU: NVIDIA GeForce RTX 4060")
print("  - CUDA Version: 12.9")
print("  - Current PyTorch: 2.1.2+cpu (CPU-only)")
print("\n" + "="*70)
print("Installation Steps:")
print("="*70)
print("\n1. Uninstall current PyTorch (CPU version):")
print("   pip uninstall torch torchvision torchaudio")
print("\n2. Install PyTorch with CUDA 12.1 support:")
print("   pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121")
print("\n   (Note: CUDA 12.1 is compatible with your CUDA 12.9 driver)")
print("\n3. Verify installation:")
print("   python test_gpu.py")
print("\n" + "="*70)
print("Alternative (if you want CUDA 11.8):")
print("="*70)
print("   pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118")
print("\n" + "="*70)
print("\nAfter installation, your training will be much faster!")
print("Expected speedup: 5-10x faster for neural network training")
print("="*70)
